### PR TITLE
Обновить query-string

### PR DESCRIPTION
**Pull request by dartess**
Закрывает https://github.com/fullstack-development/build-route-tree/issues/8

### CODE REVIEW

**Comment by Znack** [comment]
@dartess sent you a maintainer invite 🚀

**Review by Znack — APPROVED** [review]

**Comment by dartess** [comment]
Is there anyone who can update the build in npm?

**Comment by Znack** [comment]
I can invite you as a maintainer to npm, what is your nickname?

**Comment by dartess** [comment]
https://www.npmjs.com/~dartess

**Comment by Znack** [comment]
image

looks like I have no permission for the invitation :( @in19farkt can you please take a look? Can you invite a new collaborator?

**Comment by in19farkt** [comment]
@Znack could you try to add a new member to the fsd developers team? https://www.npmjs.com/settings/fullstack-development/teams/team/developers/users

**Comment by in19farkt** [comment]
@Znack I also can't invite a new member 🤷‍♂️
image

**Comment by dartess** [comment]
Can any of you publish it?

**Comment by Znack** [comment]
> @Znack could you try to add a new member to the fsd developers team? https://www.npmjs.com/settings/fullstack-development/teams/team/developers/users

Did it. @dartess please check out your inbox, the invitation must be there

**Comment by Znack** [comment]
image

Looks like you are collaborator now @dartess :)

**Comment by dartess** [comment]
Thanks, I'll keep an eye on it
I'll make a release a little later

**Pull request merged**
